name: Android CI — Build APK

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: 'platforms;android-34,build-tools;34.0.0,platform-tools'

      - name: Gradle build (no wrapper)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.5
          arguments: assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: A52AI-v3_1-debug-apk
          path: app/build/outputs/apk/debug/**/*.apk
